id = "cairo"
name = "Cairo"
version = "0.0.4"
schema_version = 1
authors = ["Thomas Robert Butler IV trbiv@proton.me", "Okhai Omotuebe okhaio@protonmail.com"]
description = "Cairo language support for the Zed editor"
repository = "https://github.com/trbutler4/zed-cairo"

[grammars.cairo]
repository = "https://github.com/starkware-libs/tree-sitter-cairo"
commit = "e3a0212261c125cb38248458cd856c0ffee2b398"

[language_servers.cairo]
name = "Cairo LSP"
language = "Cairo"
